server:
  port: 8080

spring:
  application:
    name: game-application
  threads:
    virtual:
      enabled: true
  datasource:
    url:  jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  cache:
    jcache:
      config: classpath:ehcache.xml	  